name: Bug report
description: Report a bug or unexpected behavior
assignees: kontang5
labels: bug
title: "Bug: "
body:
  - type: input
    id: overview
    attributes:
      label: Overview
      description: A brief summary of the bug.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Step-by-step description of how to reproduce the bug.
      placeholder: |
        1.
        2.
        3.
        ...
      render: bash
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Outcome
      description: Description of the expected behavior.
      placeholder: |
        A description of what you expected to happen.
        
        Example: "The expected behavior is that [...]"
      render: markdown
    validations:
        required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Logs from the application.
      render: bash
      placeholder: |
        # Include relevant code or logs here
    validations:
        required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other context, screenshots, or relevant details.
    validations:
        required: false
