name: Feature request
description: Suggesting a new feature
assignees: kontang5
labels: enhancement
title: "Feature: "
body:
  - type: textarea
    id: overview
    attributes:
      label: Overview
      description: What feature do you want and why?
      placeholder: |
        Briefly describe the feature and its purpose.
        
        Example: "Add dark mode because working at night hurts my eyes"
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: Describe how the feature could be implemented.
      placeholder: |
        Explain how the idea could be realized clearly.
        
        Example: "The feature will be implemented by [...]"
      render: markdown
    validations:
        required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other context, screenshots, or relevant details.
    validations:
        required: false


