name: Other
description: Anything else (notes, ideas, reminders)
assignees: kontang5
labels: misc
title: ""
body:
  - type: textarea
    id: content
    attributes:
      label: Details
    validations:
      required: true