name: Optimization
description: Performance or efficiency improvements
assignees: kontang5
labels: optimization
title: "Optimize: "
body:
  - type: textarea
    id: problem
    attributes:
      label: Current Issue
      description: What's slow, inefficient, or could be better?
      placeholder: |
        Describe the bottleneck or inefficiency.
        
        Example: "Dashboard loads in 3s because we fetch all 10k users at once"
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How could this be improved?
      placeholder: |
        Your idea for optimization.
        
        Example: "Implement pagination + lazy loading → reduce to 50 users per page"
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Expected Impact
      description: What improvement do you expect?
      placeholder: |
        Estimated gains or metrics.
        
        Example: "Should reduce load time from 3s to <500ms"
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Additional Context
      description: Benchmarks, profiling data, references, or trade-offs
    validations:
      required: false